---
apiVersion: v1
kind: Service
metadata:
  name: fibonacci
  namespace: "{{ .Values.klt.stage }}"
spec:
  type: ClusterIP
  selector:
    app: fibonacci
  ports:
  - name: http
    port: 30001
    targetPort: 30001