apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
stringData:
  dt-env: "DT_TENANT_TO_REPLACE"
  dt-api-token: "DT_TOKEN_TO_REPLACE"
  webhook-env: "https://webhook.site/YOUR-ID-HERE"
type: Opaque
