apiVersion: v1
kind: ConfigMap
metadata:
  name: feature-flags
  namespace: "{{ .Values.namespace }}"
data:
  config.json: |-
    {
      "flags": {
        "new-welcome-message": {
          "state": "ENABLED",
          "variants": {
            "on": true,
            "off": false
          },
          "defaultVariant": "on"
        },
        "hex-color": {
          "returnType": "string",
          "variants": {
            "red": "c05543",
            "green": "2f5230",
            "blue": "0d507b"
          },
          "defaultVariant": "blue",
          "state": "ENABLED"
        },
        "use-remote-fib-service": {
          "state": "ENABLED",
          "variants": {
            "on": true,
            "off": false
          },
          "defaultVariant": "off",
          "targeting": {
            "if": [{
                "in": ["k6", {
                  "var": ["userAgent"]
                }]
              },
              "on",
              null
            ]
          }
        },
        "fib-algo": {
          "returnType": "string",
          "variants": {
            "recursive": "recursive",
            "memo": "memo",
            "loop": "loop",
            "binet": "binet"
          },
          "defaultVariant": "recursive",
          "state": "ENABLED",
          "targeting": {
            "if": [
              { "in": ["@faas.com", { "var": "email" }] },
              "binet",
              { "in": ["k6", { "var": "userAgent" }] },
              "binet",
              null
            ]
          }
        }
      }
    }
