---
apiVersion: v1
kind: Service
metadata:
  name: fib3r
  namespace: "{{ .Values.namespace }}"
spec:
  type: LoadBalancer
  selector:
    app: fib3r
  ports:
  - name: http
    port: 80
    targetPort: 30000